data:
  dataset: {name: mnist, samples: 70000, type: public}
  datasetLoadOption: full
  kfold: 1
  mapping:
    Digit Label:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
    Image:
      options: {Augmentation: false, Height: 28, Normalization: false, Resize: false,
        Scaling: 1, Width: 28, height_shift_range: 0, horizontal_flip: false, pretrained: None,
        rotation_range: 0, shear_range: 0, vertical_flip: false, width_shift_range: 0}
      port: InputPort0
      shape: ''
      type: Image
  numPorts: 1
  samples: {split: 5, test: 3500, training: 63000, validation: 3500}
  shuffle: false
model:
  connections:
  - {source: LSTM_9, target: Dense_1}
  - {source: Reshape_1, target: LSTM_9}
  - {source: Input_1, target: BatchNormalization_1}
  - {source: BatchNormalization_1, target: Reshape_1}
  - {source: Dense_1, target: Output_1}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 5.01
    y: 37.33
  - args: {}
    class: Output
    name: Output_1
    x: 369.5400000000003
    y: 451.3999999999999
  - args: {activation: softmax, output_dim: '10'}
    class: Dense
    name: Dense_1
    x: 363.18999999999994
    y: 354.54
  - args: {target_shape: '(28,28)'}
    class: Reshape
    name: Reshape_1
    x: 4.68
    y: 221.32999999999998
  - args: {}
    class: BatchNormalization
    name: BatchNormalization_1
    x: 4.68
    y: 124.51000000000002
  - args: {output_dim: '128'}
    class: LSTM
    name: LSTM_9
    x: 356
    y: 166
params:
  advance_params: true
  batch_size: 32
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 10
  optimizer: {name: Adadelta}
project: MNIST Handwritten Digits my
